patch & program build system was reworked

diff --git a/icp b/icp
--- a/icp
+++ b/icp
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Reinstall custom programs
+
 function die {
     echo -e "\033[31m$(basename $0): ${1:-"Unknown Error"}\033[0m" 1>&2
     exit 1
@@ -7,22 +9,74 @@ function die {
 
 function checkresult {
 	if [ $? -ne 0 ]; then
-		echo -e "\033[31m$(basename $0): failed!\033[0m" 1>&2
+		echo -e "\033[31m$(basename $0): REBUILDING FAILED!\033[0m" 1>&2
 		exit 1
    	fi
 }
 
-# >>> installing packages
-
 REPOS_PATH="/home/plux/Dropbox/Repositories"
 ENV_PATH="$REPOS_PATH/environment-plux"
+SCRIPTS="$ENV_PATH/scripts/static/build"
+PRG_PATH="$ENV_PATH/programs"
 
-dpkg -i $ENV_PATH/programs/dwm-6.0/packages/*.deb
+# >>> dwm
+
+cd $ENV_PATH
+
+REPO_PATH="$REPOS_PATH/dwm-6.0-plux"
+
+$SCRIPTS/mergebranches "$PRG_PATH" "dwm-6.0" "$REPO_PATH"
 checkresult
 
-dpkg -i $ENV_PATH/programs/dmenu-4.5/packages/*.deb
+$SCRIPTS/genpatches "$PRG_PATH" "dwm-6.0" "$REPO_PATH"
 checkresult
 
-dpkg -i $ENV_PATH/programs/st-0.4.1/packages/*.deb
+$SCRIPTS/patchinstall "$PRG_PATH" "dwm-6.0"
 checkresult
 
+# >>> dmenu
+
+cd $ENV_PATH
+
+REPO_PATH="$REPOS_PATH/dmenu-4.5-plux"
+
+$SCRIPTS/mergebranches "$PRG_PATH" "dmenu-4.5" "$REPO_PATH"
+checkresult
+
+$SCRIPTS/genpatches "$PRG_PATH" "dmenu-4.5" "$REPO_PATH"
+checkresult
+
+$SCRIPTS/patchinstall "$PRG_PATH" "dmenu-4.5"
+checkresult
+
+# >>> st
+
+cd $ENV_PATH
+
+REPO_PATH="$REPOS_PATH/st-0.4.1-plux"
+
+$SCRIPTS/mergebranches "$PRG_PATH" "st-0.4.1" "$REPO_PATH"
+checkresult
+
+$SCRIPTS/genpatches "$PRG_PATH" "st-0.4.1" "$REPO_PATH"
+checkresult
+
+$SCRIPTS/patchinstall "$PRG_PATH" "st-0.4.1"
+checkresult
+
+# >>> slock 
+
+cd $ENV_PATH
+
+REPO_PATH="$REPOS_PATH/slock-1.1-plux"
+
+$SCRIPTS/mergebranches "$PRG_PATH" "slock-1.1" "$REPO_PATH"
+checkresult
+
+$SCRIPTS/genpatches "$PRG_PATH" "slock-1.1" "$REPO_PATH"
+checkresult
+
+$SCRIPTS/patchinstall "$PRG_PATH" "slock-1.1"
+checkresult
+
+exit 0
